# Таблица orderitems

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
df_oi = pd.read_csv('../raw_data/df_OrderItems.csv')

In [35]:
df_oi.shape

(89316, 5)

In [36]:
df_oi.size

446580

In [37]:
df_oi.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [38]:
df_oi.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [39]:
df_oi.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [40]:
df_oi.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [41]:
df_oi.sample(10)

           order_id    product_id     seller_id   price  shipping_charges
76473  UqohC3MPkEtH  6XfYPg0BbmRZ  kiirS0of7bJI   72.40              2.75
13302  QwTEwjCtyrxG  UgkSjxoiV9Ev  UOGIrJtSldvd  252.99             50.83
75243  oS4kO6CE1rMy  JyZ2lz9d7fe7  yHsOFiqVrV1u   49.38             52.74
19621  iGuc9CViynOW  Hm9mFJBvMigB  eAcHTmATevNi   82.91             19.38
53469  Ap5uJH6yCUCq  GmgXGONutNxg  BGPWBRIq3VJB   28.70             12.63
37382  72Hx64ESfqf7  upRhLUhl2Z9D  QuHzyl7PHuUt  137.88             19.38
6759   eZgndl2fHDfM  7UiVFZaNvsao  AHG0TE6bRNNY  128.99             21.54
9722   jswo5q77XmMq  huOtiYFnpes9  CYe0rVOTbNZ3  465.52             63.44
64078  2BwGr157VHTP  xdrZncPeF7MD  SgeUigb5Vbiv   16.20             30.39
80195  RjPXWS1F5day  FOl7uWQPiFgM  rFT13UJuGo0Q   35.19             22.46

In [42]:
# проверим есть ли пустые значения
df_oi.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [43]:
# проверим на уникальность
df_oi.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [44]:
# проверим дубликаты
df_oi.duplicated().sum()

np.int64(0)

In [45]:
# статистика по цифровым показателям
df_oi.describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

In [46]:
# проверим дубли составного ключа
df_oi.groupby(['order_id', 'product_id']).size().shape[0]

89316

In [47]:
#  посмотрим количество позиций в заказе
df_oi.groupby('order_id').size().describe()

# в каждом заказе ровно по одной позиции, т.е. все заказы однопозиционные

count    89316.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [48]:
# проверим нули в данных
df_oi.query('shipping_charges == 0').order_id.count()

np.int64(22)

In [49]:
df_oi.query('shipping_charges == 0').describe()

# нулевая доставка (0.025% от общего числа заказов) возможно была из-за самовывоза (дешевые товары)
# или включенной в стоимость товара (дорогие товары)
# в данном датасете нет возможности уточнить этот пункт

             price  shipping_charges
count    22.000000              22.0
mean    236.137273               0.0
std     416.899028               0.0
min      19.980000               0.0
25%      71.800000               0.0
50%     119.070000               0.0
75%     176.145000               0.0
max    1949.900000               0.0

In [50]:
# проверим аномальные цены
quantiles = df_oi[['price', 'shipping_charges']].quantile([0.01, 0.25, 0.5, 0.75, 0.99])
quantiles

        price  shipping_charges
0.01     7.78             1.870
0.25    59.65            20.110
0.50   136.90            35.055
0.75   399.20            57.190
0.99  2899.00           181.880

In [51]:
iqr_price = quantiles.loc[0.75, 'price'] - quantiles.loc[0.25, 'price']
iqe_shipping_charges = quantiles.loc[0.75, 'shipping_charges'] - quantiles.loc[0.25, 'shipping_charges']

In [52]:
low_limit_price = quantiles.loc[0.25, 'price'] - 1.5 * iqr_price
high_limit_price = quantiles.loc[0.75, 'price'] + 1.5 * iqr_price

print(f'Нижняя граница {low_limit_price.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_price.round(2)}')

Нижняя граница -449.68
Верхняя граница 908.53

In [53]:
low_limit_ship_charge = quantiles.loc[0.25, 'shipping_charges'] - 1.5 * iqe_shipping_charges
high_limit_ship_charge = quantiles.loc[0.75, 'shipping_charges'] + 1.5 * iqe_shipping_charges

print(f'Нижняя граница {low_limit_ship_charge.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_ship_charge.round(2)}')

Нижняя граница -35.51
Верхняя граница 112.81

In [54]:
# кол-во price выше верхней границы
df_oi.query('price > @high_limit_price').shape[0]

5798

In [55]:
# кол-во shipping_charges выше верхней границы
df_oi.query('shipping_charges > @high_limit_ship_charge').shape[0]

4615

In [56]:
# проверим, что цены и расходы на логистику совпадают с оплатами
df_oi['total_amount'] = df_oi['price'] + df_oi['shipping_charges']
df_oi

,order_id,product_id,seller_id,price,shipping_charges,total_amount
0,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16
1,v6px92oS8cLG,qejhpMGGVcsl,IjlpYfhUbRQs,170.80,23.79,194.59
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,77p2EYxcM9MD,64.40,17.38,81.78
3,bwJVWupf2keN,639iGvMyv0De,jWzS0ayv9TGf,264.50,30.72,295.22
4,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.90,30.66,810.56
...,...,...,...,...,...,...
89311,zlcLnXGgAabl,W8vikEizUggJ,2QjevWskirjm,31.99,188.65,220.64
89312,IlTAoIkILwrq,KXSbyJWtMMwZ,BFS9XJPapWv0,282.00,1.64,283.64
89313,uA6oXfftGVmT,EG4wDSpFyTth,TuPm19CMKvrM,58.10,4.09,62.19
89314,v3QtU6xlGDJp,ZWyg4uNWPHjJ,yGbPyLPc8PmT,2899.00,113.01,3012.01
89315,Xo1fqyXOC6CR,5pbzE0rDy61l,mkWN70fui2ro,37.88,70.06,107.94

In [57]:
df_oi['order_id'].nunique()

89316

In [58]:
df_p_clean = pd.read_pickle('df_p_clean.pkl')
df_p_clean.head()

# помним, что из таблицы оплат удалены заказы, по которым в таблице df_o были выявлены аномальные даты

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [59]:
df_p_clean.shape[0]

89186

In [66]:
df_oipay = df_oi.merge(df_p_clean, on='order_id', how='inner')
df_oipay[['order_id', 'total_amount', 'payment_value']]

           order_id  total_amount  payment_value
0      Axfy13Hk4PIk        308.16         259.14
1      v6px92oS8cLG        194.59         382.39
2      Ulpf9skrhjfm         81.78         249.25
3      bwJVWupf2keN        295.22          27.79
4      Dd0QnrMk9Cj5        810.56          76.15
...             ...           ...            ...
89181  zlcLnXGgAabl        220.64         128.00
89182  IlTAoIkILwrq        283.64         106.86
89183  uA6oXfftGVmT         62.19         376.39
89184  v3QtU6xlGDJp       3012.01          48.05
89185  Xo1fqyXOC6CR        107.94         211.93

[89186 rows x 3 columns]

In [63]:
df_oi[df_oi['order_id'] == 'Axfy13Hk4PIk']

,order_id,product_id,seller_id,price,shipping_charges,total_amount
0,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16

In [64]:
df_p_clean[df_p_clean['order_id'] == 'Axfy13Hk4PIk']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14

In [67]:
df_oi[df_oi['order_id'] == 'Dd0QnrMk9Cj5']

,order_id,product_id,seller_id,price,shipping_charges,total_amount
4,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.9,30.66,810.56

In [68]:
df_p_clean[df_p_clean['order_id'] == 'Dd0QnrMk9Cj5']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [72]:
df_oipay['is_anomaly_price'] = df_oipay['payment_value'] < df_oipay['price']
df_oipay['is_anomaly_price_shipping'] = df_oipay['payment_value'] < df_oipay['total_amount']
df_oipay[['order_id', 'is_anomaly_price', 'is_anomaly_price_shipping']]

           order_id  is_anomaly_price  is_anomaly_price_shipping
0      Axfy13Hk4PIk             False                       True
1      v6px92oS8cLG             False                      False
2      Ulpf9skrhjfm             False                      False
3      bwJVWupf2keN              True                       True
4      Dd0QnrMk9Cj5              True                       True
...             ...               ...                        ...
89181  zlcLnXGgAabl             False                       True
89182  IlTAoIkILwrq              True                       True
89183  uA6oXfftGVmT             False                      False
89184  v3QtU6xlGDJp              True                       True
89185  Xo1fqyXOC6CR             False                      False

[89186 rows x 3 columns]

In [86]:
price_anomalies = df_oipay['is_anomaly_price'].sum()
shipping_anomalies = df_oipay['is_anomaly_price_shipping'].sum()

print(f"Аномалий цены: {price_anomalies}")
print(f"Аномалий с доставкой: {shipping_anomalies}")

Аномалий цены: 42497
Аномалий с доставкой: 49799

In [92]:
anomaly_table = pd.DataFrame({
    'Тип аномалии': ['Ценовая аномалия (price)', 'Аномалия доставки (shipping)'],
    'Количество': [price_anomalies, shipping_anomalies],
    'Процент': [
        round(price_anomalies / len(df_oipay) * 100, 2),
        round(shipping_anomalies / len(df_oipay) * 100, 2)
    ]
})

anomaly_table

                   Тип аномалии  Количество  Процент
0      Ценовая аномалия (price)       42497    47.65
1  Аномалия доставки (shipping)       49799    55.84

In [83]:
# суммы по прайсам (предположим, что доставка включена в цену товара)
sum_price_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'price'].sum()
sum_price_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'price'].sum()

# суммы по прайсам + логистика
sum_total_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'total_amount'].sum()
sum_total_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'total_amount'].sum()

# суммы оплат от клиентов по заказам
sum_payment_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'payment_value'].sum()
sum_payment_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'payment_value'].sum()

print(f'Сумма аномальной стоимости заказов (доставка в цене): {sum_price_anomaly_true:,.2f}')
print(f'Сумма корректной стоимости заказов (доставка в цене): {sum_price_anomaly_false:,.2f}')
print(f'Общая сумма стоимости заказов (доставка в цене): {sum_price_anomaly_true + sum_price_anomaly_false:,.2f}')
print()
print(f'Сумма аномальной стоимости заказов (доставка отдельно): {sum_total_anomaly_true:,.2f}')
print(f'Сумма корректной стоимости заказов (доставка отдельно): {sum_total_anomaly_false:,.2f}')
print(f'Общая сумма стоимости заказов (доставка отдельно): {sum_total_anomaly_true + sum_total_anomaly_false:,.2f}')
print()
print(f'Сумма оплат клиентами: {sum_payment_anomaly_true:,.2f}')
print(f'Сумма оплат клиентами: {sum_payment_anomaly_false:,.2f}')
print(f'Общая сумма оплат клиентами: {sum_payment_anomaly_true + sum_payment_anomaly_false:,.2f}')

Сумма аномальной стоимости заказов (доставка в цене): 25,271,391.81
Сумма корректной стоимости заказов (доставка в цене): 5,135,498.47
Общая сумма стоимости заказов (доставка в цене): 30,406,890.28

Сумма аномальной стоимости заказов (доставка отдельно): 27,132,999.83
Сумма корректной стоимости заказов (доставка отдельно): 7,224,220.51
Общая сумма стоимости заказов (доставка отдельно): 34,357,220.34

Сумма оплат клиентами: 6,106,033.95
Сумма оплат клиентами: 17,855,323.74
Общая сумма оплат клиентами: 23,961,357.69

In [ ]:
df_oipay['price_diff'] = df_oipay['price'] - df_oipay['payment_value']
df_oipay['price_diff'].describe()

# Если price_diff > 0 → клиент заплатил меньше, чем цена
# Если price_diff < 0 → клиент заплатил больше, чем цена

count    89186.000000
mean        72.270677
std        651.128510
min      -7049.730000
25%       -160.120000
50%        -12.250000
75%        187.310000
max       6669.520000
Name: price_diff, dtype: float64

In [ ]:
stats_anomaly = df_oipay.loc[df_oipay['is_anomaly_price'], 'price_diff'].describe()
stats_anomaly

# В половине «аномальных» заказов недоплата ≥ ≈208 единиц.
# В четверти — недоплата ≥ ≈527.
# Есть хвост до ≈6.7K.

count    42497.000000
mean       450.981431
std        674.064074
min          0.010000
25%         66.400000
50%        208.670000
75%        526.830000
max       6669.520000
Name: price_diff, dtype: float64

In [ ]:
stats_ok = df_oipay.loc[~df_oipay['is_anomaly_price'], 'price_diff'].describe()
stats_ok

# Во всех этих заказах payment_value ≥ price, и price_diff ≤ 0.
# Медианная переплата ≈150.76, четверть заказов имеет переплату ≥≈308 по модулю.
# Хвост переплат до ≈7K.

count    46689.000000
mean      -272.437304
std        383.326010
min      -7049.730000
25%       -307.700000
50%       -150.760000
75%        -68.050000
max          0.000000
Name: price_diff, dtype: float64