# Таблица OrderItems

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df_oi = pd.read_csv('../raw_data/df_OrderItems.csv')

In [3]:
df_oi.shape

(89316, 5)

In [4]:
df_oi.size

446580

In [6]:
df_oi.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [7]:
df_oi.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [8]:
df_oi.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [9]:
df_oi.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [10]:
df_oi.sample(10)

           order_id    product_id     seller_id    price  shipping_charges
70839  VKXHeyRybQlA  qLtu3LpSFE66  6ywUQmf7ylJv    33.80            105.70
8826   RddtY72Cjpfx  7AkukUOepPs4  cUodQhgpRajF   145.99             15.67
58446  BGmu9sp32SbJ  7lPzFAjT1x1Q  ux1d7N0zioFv   319.29             68.99
2565   CfsFLa7bor7a  k1G4RHt3R7Nk  K0qPVGdA91KO  1589.00             38.66
27219  SYIIVN23bePj  9SOPBqeEKe4d  NPzG9GmZi6FT    18.04             20.93
79507  q0KvM3muV5Mn  zvn2wo7ja8VG  Izazx5OLdwb0    30.80              6.37
75460  U1oKjikvV6Ow  89oT9Pz9eQaA  7OKhjPME8ZK3   274.49              7.77
76578  EgyWZm3Q8PCz  Rb4Cu9E08yEW  n71QJUsiY2v9    31.58            155.82
62280  RDlode89VuN2  2VekIbjk72E1  5ogCnwzSomBT   712.50              2.93
30410  JH7AYhofhq8R  UgkSjxoiV9Ev  UOGIrJtSldvd   252.99             50.83

In [ ]:
# проверим есть ли пустые значения
df_oi.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [14]:
# проверим на уникальность
df_oi.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [17]:
# проверим дубликаты
df_oi.duplicated().sum()

np.int64(0)

In [ ]:
# статистика по цифровым показателям
df_oi.describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000