# Таблица orderitems

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_oi = pd.read_csv('../raw_data/df_OrderItems.csv')

In [3]:
df_oi.shape

(89316, 5)

In [4]:
df_oi.size

446580

In [5]:
df_oi.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [6]:
df_oi.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [7]:
df_oi.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [8]:
df_oi.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [9]:
df_oi.sample(10)

           order_id    product_id     seller_id   price  shipping_charges
10478  sCYGbmJTxQ28  Mn5rxwsJ7qI3  wdkFVpIzRNT3  222.98              6.08
55458  iHkKuHSJIE83  bng1qJfjWdWw  4YvZWfI3A03T  410.00              7.94
15411  f0ClEUBNBh6p  wjBKQjz1cxME  A7s2wiNKJ3HW  839.99             44.91
26843  xeEISGa5b4PT  RtVizzAZEByU  WFBPWdo5flxA   50.21              1.05
82115  Ntpr0Wao7RNU  xnJD4OGInSjk  5Ja2lH0N2OZt   19.30             44.40
32149  tPDRG7vcJOiT  ro08JPncYzLh  r7VxefoTVHbb  509.99             17.44
13542  POClcgoQZYuQ  oyHRoKBexOF0  AvTLykupHOIB  820.05             30.46
3382   UMNBCnefiUCf  nsAGizMOhDfU  TONxC5aLQqev    8.65             32.34
82979  TbVqz0mdauC2  L2PXExQYtPnk  rTKC7c3Tt984   26.77              9.45
11752  MqWsHCR5OkVf  gveQR41JRbKO  9GqaJH04uktb  329.93             19.90

In [10]:
# проверим есть ли пустые значения
df_oi.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [11]:
# проверим на уникальность
df_oi.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [12]:
# проверим дубликаты
df_oi.duplicated().sum()

np.int64(0)

In [13]:
# статистика по цифровым показателям
df_oi.describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

In [14]:
# проверим дубли составного ключа
df_oi.groupby(['order_id', 'product_id']).size().shape[0]

89316

In [15]:
#  посмотрим количество позиций в заказе
df_oi.groupby('order_id').size().describe()

# в каждом заказе ровно по одной позиции, т.е. все заказы однопозиционные

count    89316.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [16]:
# проверим нули в данных
df_oi.query('shipping_charges == 0').order_id.count()

np.int64(22)

In [17]:
df_oi.query('shipping_charges == 0').describe()

# нулевая доставка (0.025% от общего числа заказов) возможно была из-за самовывоза (дешевые товары)
# или включенной в стоимость товара (дорогие товары)
# в данном датасете нет возможности уточнить этот пункт

             price  shipping_charges
count    22.000000              22.0
mean    236.137273               0.0
std     416.899028               0.0
min      19.980000               0.0
25%      71.800000               0.0
50%     119.070000               0.0
75%     176.145000               0.0
max    1949.900000               0.0

In [18]:
# проверим аномальные цены
quantiles = df_oi[['price', 'shipping_charges']].quantile([0.01, 0.25, 0.5, 0.75, 0.99])
quantiles

        price  shipping_charges
0.01     7.78             1.870
0.25    59.65            20.110
0.50   136.90            35.055
0.75   399.20            57.190
0.99  2899.00           181.880

In [19]:
iqr_price = quantiles.loc[0.75, 'price'] - quantiles.loc[0.25, 'price']
iqe_shipping_charges = quantiles.loc[0.75, 'shipping_charges'] - quantiles.loc[0.25, 'shipping_charges']

In [20]:
low_limit_price = quantiles.loc[0.25, 'price'] - 1.5 * iqr_price
high_limit_price = quantiles.loc[0.75, 'price'] + 1.5 * iqr_price

print(f'Нижняя граница {low_limit_price.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_price.round(2)}')

Нижняя граница -449.68
Верхняя граница 908.53

In [21]:
low_limit_ship_charge = quantiles.loc[0.25, 'shipping_charges'] - 1.5 * iqe_shipping_charges
high_limit_ship_charge = quantiles.loc[0.75, 'shipping_charges'] + 1.5 * iqe_shipping_charges

print(f'Нижняя граница {low_limit_ship_charge.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_ship_charge.round(2)}')

Нижняя граница -35.51
Верхняя граница 112.81

In [22]:
# кол-во price выше верхней границы
df_oi.query('price > @high_limit_price').shape[0]

5798

In [23]:
# кол-во shipping_charges выше верхней границы
df_oi.query('shipping_charges > @high_limit_ship_charge').shape[0]

4615

In [24]:
# проверим, что цены и расходы на логистику совпадают с оплатами
df_oi['total_amount'] = df_oi['price'] + df_oi['shipping_charges']
df_oi

,order_id,product_id,seller_id,price,shipping_charges,total_amount
0,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16
1,v6px92oS8cLG,qejhpMGGVcsl,IjlpYfhUbRQs,170.80,23.79,194.59
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,77p2EYxcM9MD,64.40,17.38,81.78
3,bwJVWupf2keN,639iGvMyv0De,jWzS0ayv9TGf,264.50,30.72,295.22
4,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.90,30.66,810.56
...,...,...,...,...,...,...
89311,zlcLnXGgAabl,W8vikEizUggJ,2QjevWskirjm,31.99,188.65,220.64
89312,IlTAoIkILwrq,KXSbyJWtMMwZ,BFS9XJPapWv0,282.00,1.64,283.64
89313,uA6oXfftGVmT,EG4wDSpFyTth,TuPm19CMKvrM,58.10,4.09,62.19
89314,v3QtU6xlGDJp,ZWyg4uNWPHjJ,yGbPyLPc8PmT,2899.00,113.01,3012.01
89315,Xo1fqyXOC6CR,5pbzE0rDy61l,mkWN70fui2ro,37.88,70.06,107.94

In [25]:
df_oi['order_id'].nunique()

89316

In [26]:
df_p_clean = pd.read_pickle('df_p_clean.pkl')
df_p_clean.head()

# помним, что из таблицы оплат удалены заказы, по которым в таблице df_o были выявлены аномальные даты

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [27]:
df_p_clean.shape[0]

89186

In [28]:
df_oipay = df_oi.merge(df_p_clean, on='order_id', how='inner')
df_oipay[['order_id', 'total_amount', 'payment_value']]

           order_id  total_amount  payment_value
0      Axfy13Hk4PIk        308.16         259.14
1      v6px92oS8cLG        194.59         382.39
2      Ulpf9skrhjfm         81.78         249.25
3      bwJVWupf2keN        295.22          27.79
4      Dd0QnrMk9Cj5        810.56          76.15
...             ...           ...            ...
89181  zlcLnXGgAabl        220.64         128.00
89182  IlTAoIkILwrq        283.64         106.86
89183  uA6oXfftGVmT         62.19         376.39
89184  v3QtU6xlGDJp       3012.01          48.05
89185  Xo1fqyXOC6CR        107.94         211.93

[89186 rows x 3 columns]

In [29]:
df_oi[df_oi['order_id'] == 'Axfy13Hk4PIk']

,order_id,product_id,seller_id,price,shipping_charges,total_amount
0,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16

In [30]:
df_p_clean[df_p_clean['order_id'] == 'Axfy13Hk4PIk']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14

In [31]:
df_oi[df_oi['order_id'] == 'Dd0QnrMk9Cj5']

,order_id,product_id,seller_id,price,shipping_charges,total_amount
4,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.9,30.66,810.56

In [32]:
df_p_clean[df_p_clean['order_id'] == 'Dd0QnrMk9Cj5']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [33]:
df_oipay['is_anomaly_price'] = df_oipay['payment_value'] < df_oipay['price']
df_oipay['is_anomaly_price_shipping'] = df_oipay['payment_value'] < df_oipay['total_amount']
df_oipay[['order_id', 'is_anomaly_price', 'is_anomaly_price_shipping']]

           order_id  is_anomaly_price  is_anomaly_price_shipping
0      Axfy13Hk4PIk             False                       True
1      v6px92oS8cLG             False                      False
2      Ulpf9skrhjfm             False                      False
3      bwJVWupf2keN              True                       True
4      Dd0QnrMk9Cj5              True                       True
...             ...               ...                        ...
89181  zlcLnXGgAabl             False                       True
89182  IlTAoIkILwrq              True                       True
89183  uA6oXfftGVmT             False                      False
89184  v3QtU6xlGDJp              True                       True
89185  Xo1fqyXOC6CR             False                      False

[89186 rows x 3 columns]

In [34]:
price_anomalies = df_oipay['is_anomaly_price'].sum()
shipping_anomalies = df_oipay['is_anomaly_price_shipping'].sum()

print(f"Аномалий цены: {price_anomalies}")
print(f"Аномалий с доставкой: {shipping_anomalies}")

Аномалий цены: 42497
Аномалий с доставкой: 49799

In [35]:
anomaly_table = pd.DataFrame({
    'Тип аномалии': ['Ценовая аномалия (price)', 'Аномалия доставки (shipping)'],
    'Количество': [price_anomalies, shipping_anomalies],
    'Процент': [
        round(price_anomalies / len(df_oipay) * 100, 2),
        round(shipping_anomalies / len(df_oipay) * 100, 2)
    ]
})

anomaly_table

                   Тип аномалии  Количество  Процент
0      Ценовая аномалия (price)       42497    47.65
1  Аномалия доставки (shipping)       49799    55.84

In [45]:
# суммы по прайсам (предположим, что доставка включена в цену товара)
sum_price_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'price'].sum()
sum_price_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'price'].sum()

# суммы по прайсам + логистика
sum_total_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'total_amount'].sum()
sum_total_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'total_amount'].sum()

# суммы оплат от клиентов по заказам
sum_payment_anomaly_true = df_oipay.loc[df_oipay['is_anomaly_price'], 'payment_value'].sum()
sum_payment_anomaly_false = df_oipay.loc[~df_oipay['is_anomaly_price'], 'payment_value'].sum()

print(f'Сумма аномальной стоимости заказов (доставка в цене): {sum_price_anomaly_true:,.2f}')
print(f'Сумма корректной стоимости заказов (доставка в цене): {sum_price_anomaly_false:,.2f}')
print(f'Общая сумма стоимости заказов (доставка в цене): {sum_price_anomaly_true + sum_price_anomaly_false:,.2f}')
print()
print(f'Сумма аномальной стоимости заказов (доставка отдельно): {sum_total_anomaly_true:,.2f}')
print(f'Сумма корректной стоимости заказов (доставка отдельно): {sum_total_anomaly_false:,.2f}')
print(f'Общая сумма стоимости заказов (доставка отдельно): {sum_total_anomaly_true + sum_total_anomaly_false:,.2f}')
print()
print(f'Сумма оплат клиентами по аномальным заказам: {sum_payment_anomaly_true:,.2f}')
print(f'Сумма оплат клиентами по корректным заказам: {sum_payment_anomaly_false:,.2f}')
print(f'Общая сумма оплат клиентами: {sum_payment_anomaly_true + sum_payment_anomaly_false:,.2f}')

Сумма аномальной стоимости заказов (доставка в цене): 25,271,391.81
Сумма корректной стоимости заказов (доставка в цене): 5,135,498.47
Общая сумма стоимости заказов (доставка в цене): 30,406,890.28

Сумма аномальной стоимости заказов (доставка отдельно): 27,132,999.83
Сумма корректной стоимости заказов (доставка отдельно): 7,224,220.51
Общая сумма стоимости заказов (доставка отдельно): 34,357,220.34

Сумма оплат клиентами по аномальным заказам: 6,106,033.95
Сумма оплат клиентами по корректным заказам: 17,855,323.74
Общая сумма оплат клиентами: 23,961,357.69

In [ ]:
df_oipay['price_diff'] = df_oipay['price'] - df_oipay['payment_value']
df_oipay['price_diff'].describe()

# Если price_diff > 0 → клиент заплатил меньше, чем цена товара
# Если price_diff < 0 → клиент заплатил больше, чем цена товара

count    89186.000000
mean        72.270677
std        651.128510
min      -7049.730000
25%       -160.120000
50%        -12.250000
75%        187.310000
max       6669.520000
Name: price_diff, dtype: float64

In [38]:
stats_anomaly = df_oipay.loc[df_oipay['is_anomaly_price'], 'price_diff'].describe()
stats_anomaly

# В половине «аномальных» заказов недоплата ≥ ≈208 единиц.
# В четверти — недоплата ≥ ≈527.
# Есть хвост до ≈6.7K.

count    42497.000000
mean       450.981431
std        674.064074
min          0.010000
25%         66.400000
50%        208.670000
75%        526.830000
max       6669.520000
Name: price_diff, dtype: float64

In [39]:
stats_ok = df_oipay.loc[~df_oipay['is_anomaly_price'], 'price_diff'].describe()
stats_ok

# Во всех этих заказах payment_value ≥ price, и price_diff ≤ 0.
# Медианная переплата ≈150.76, четверть заказов имеет переплату ≥≈308 по модулю.
# Хвост переплат до ≈7K.

count    46689.000000
mean      -272.437304
std        383.326010
min      -7049.730000
25%       -307.700000
50%       -150.760000
75%        -68.050000
max          0.000000
Name: price_diff, dtype: float64

In [55]:
# соберем витрину с заказами, оплатами и скрытыми скидками
fact_orders_finance  = df_oipay[['order_id', 'product_id', 'price', 'shipping_charges', 'total_amount', 'payment_value']]
fact_orders_finance

,order_id,product_id,price,shipping_charges,total_amount,payment_value
0,Axfy13Hk4PIk,90K0C1fIyQUf,223.51,84.65,308.16,259.14
1,v6px92oS8cLG,qejhpMGGVcsl,170.80,23.79,194.59,382.39
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,64.40,17.38,81.78,249.25
3,bwJVWupf2keN,639iGvMyv0De,264.50,30.72,295.22,27.79
4,Dd0QnrMk9Cj5,1lycYGcsic2F,779.90,30.66,810.56,76.15
...,...,...,...,...,...,...
89181,zlcLnXGgAabl,W8vikEizUggJ,31.99,188.65,220.64,128.00
89182,IlTAoIkILwrq,KXSbyJWtMMwZ,282.00,1.64,283.64,106.86
89183,uA6oXfftGVmT,EG4wDSpFyTth,58.10,4.09,62.19,376.39
89184,v3QtU6xlGDJp,ZWyg4uNWPHjJ,2899.00,113.01,3012.01,48.05
89185,Xo1fqyXOC6CR,5pbzE0rDy61l,37.88,70.06,107.94,211.93

In [72]:
fact_orders_finance['hidden_discount_abs'] = fact_orders_finance['total_amount'] - fact_orders_finance['payment_value']
fact_orders_finance['hidden_discount_pct '] = round(fact_orders_finance['hidden_discount_abs'] / fact_orders_finance['total_amount'] * 100)
fact_orders_finance['payment_ratio_pct'] = round(fact_orders_finance['payment_value'] / fact_orders_finance['total_amount'] * 100)

In [75]:
fact_orders_finance = fact_orders_finance.drop(columns='payment_ratio ')

In [83]:
fact_orders_finance.describe()

,price,shipping_charges,total_amount,payment_value,hidden_discount_abs,hidden_discount_pct,payment_ratio_pct
count,89186.000000,89186.000000,89186.000000,89186.000000,89186.000000,89186.000000,89186.000000
mean,340.937931,44.293163,385.231094,268.667254,116.563840,-100.496704,200.496704
std,557.560558,37.687210,558.594157,344.462380,651.747581,922.146356,922.146356
min,0.850000,0.000000,1.140000,0.010000,-7043.080000,-174439.000000,0.000000
25%,59.650000,20.110000,107.710000,84.385000,-118.277500,-98.000000,28.000000
50%,136.900000,35.060000,184.650000,171.860000,30.640000,19.000000,81.000000
75%,399.200000,57.210000,437.860000,313.530000,236.770000,72.000000,198.000000
max,6735.000000,409.680000,6738.820000,7274.880000,6673.340000,100.000000,174539.000000

In [ ]:
# 1. Определяем границы бинов (в процентах)
bins = [-100, 0, 10, 20, 30, 50, 100, 1000]
labels = [
    '≤0% (нет скидки / переплата)',
    '0–10%',
    '10–20%',
    '20–30%',
    '30–50%',
    '50–100%',
    '>100% (аномалия)'
]

# 2. Создаём категориальный столбец
fact_orders_finance['hidden_discount_band'] = pd.cut(
    fact_orders_finance['hidden_discount_pct '],
    bins=bins,
    labels=labels,
    right=True,
    include_lowest=True
)

# 3. Считаем распределение по бинам
discount_dist = (
    fact_orders_finance['hidden_discount_band']
    .value_counts(dropna=False)
    .to_frame('orders_count')
    .assign(share_pct=lambda df: df['orders_count'] / df['orders_count'].sum() * 100)
    .sort_index()
)

discount_dist

# «номинал» (total_amount) существенно выше фактической оплаты
# либо платформа/маркетплейс активно субсидирует,
# либо прайс-лист сильно завышен и всегда продаётся «со скидкой»

                              orders_count  share_pct
hidden_discount_band
≤0% (нет скидки / переплата)         17489  19.609580
0–10%                                 2745   3.077837
10–20%                                2735   3.066625
20–30%                                3284   3.682192
30–50%                                7352   8.243446
50–100%                              33576  37.647164
>100% (аномалия)                         0   0.000000
NaN                                  22005  24.673155

In [85]:
df_nan = fact_orders_finance[fact_orders_finance['hidden_discount_pct '].isna()].copy()
df_not_nan = fact_orders_finance[fact_orders_finance['hidden_discount_pct '].notna()].copy()

In [86]:
df_nan

Empty DataFrame
Columns: [order_id, product_id, price, shipping_charges, total_amount, payment_value, hidden_discount_abs, hidden_discount_pct , payment_ratio_pct, hidden_discount_band]
Index: []

In [92]:
df_not_nan.head()

,order_id,product_id,price,shipping_charges,total_amount,payment_value,hidden_discount_abs,hidden_discount_pct,payment_ratio_pct,hidden_discount_band
0,Axfy13Hk4PIk,90K0C1fIyQUf,223.51,84.65,308.16,259.14,49.02,16.0,84.0,10–20%
1,v6px92oS8cLG,qejhpMGGVcsl,170.80,23.79,194.59,382.39,-187.80,-97.0,197.0,≤0% (нет скидки / переплата)
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,64.40,17.38,81.78,249.25,-167.47,-205.0,305.0,NaN
3,bwJVWupf2keN,639iGvMyv0De,264.50,30.72,295.22,27.79,267.43,91.0,9.0,50–100%
4,Dd0QnrMk9Cj5,1lycYGcsic2F,779.90,30.66,810.56,76.15,734.41,91.0,9.0,50–100%

In [88]:
# 1. Проверяем наличие NaN именно в биннинге
fact_orders_finance['hidden_discount_band'].isna().sum()

# 2. Смотрим экстремальные значения hidden_discount_pct
fact_orders_finance['hidden_discount_pct '].describe()

fact_orders_finance['hidden_discount_pct '].min(), fact_orders_finance['hidden_discount_pct '].max()

(np.float64(-174439.0), np.float64(100.0))

In [89]:
# 3. Посмотреть строки, которые не попали в бин (band = NaN)
df_band_nan = fact_orders_finance[fact_orders_finance['hidden_discount_band'].isna()].copy()
df_band_nan[['total_amount', 'payment_value', 'hidden_discount_abs', 'hidden_discount_pct ']].describe()

       total_amount  payment_value  hidden_discount_abs  hidden_discount_pct
count  22005.000000   22005.000000         22005.000000          22005.000000
mean     118.740224     555.206782          -436.466557           -513.160782
std      101.092103     516.379126           472.804547           1792.098527
min        1.140000      33.480000         -7043.080000        -174439.000000
25%       60.010000     245.570000          -509.730000           -527.000000
50%       93.320000     384.860000          -271.180000           -278.000000
75%      146.000000     656.810000          -162.250000           -164.000000
max     1702.950000    7274.880000           -19.890000           -101.000000

In [93]:
fact_orders_finance['discount_type'] = np.where(
    fact_orders_finance['hidden_discount_pct '] < -100,
    'overpay_or_miscalc',      # заплатили намного больше номинала / проблема расчёта
    'normal_or_discount'       # всё остальное
)
fact_orders_finance.head()

,order_id,product_id,price,shipping_charges,total_amount,payment_value,hidden_discount_abs,hidden_discount_pct,payment_ratio_pct,hidden_discount_band,discount_type
0,Axfy13Hk4PIk,90K0C1fIyQUf,223.51,84.65,308.16,259.14,49.02,16.0,84.0,10–20%,normal_or_discount
1,v6px92oS8cLG,qejhpMGGVcsl,170.80,23.79,194.59,382.39,-187.80,-97.0,197.0,≤0% (нет скидки / переплата),normal_or_discount
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,64.40,17.38,81.78,249.25,-167.47,-205.0,305.0,NaN,overpay_or_miscalc
3,bwJVWupf2keN,639iGvMyv0De,264.50,30.72,295.22,27.79,267.43,91.0,9.0,50–100%,normal_or_discount
4,Dd0QnrMk9Cj5,1lycYGcsic2F,779.90,30.66,810.56,76.15,734.41,91.0,9.0,50–100%,normal_or_discount

In [94]:
discount_type_counts = (
    fact_orders_finance['discount_type']
    .value_counts(dropna=False)
    .to_frame('rows_count')
    .assign(share_pct=lambda df: df['rows_count'] / df['rows_count'].sum() * 100)
)

discount_type_counts

                    rows_count  share_pct
discount_type
normal_or_discount       67181  75.326845
overpay_or_miscalc       22005  24.673155

In [100]:
# посмотрим есть ли зависимость скидки от типа оплаты
# пример: берём payment_type платежа с максимальным payment_value
payments_main = (
    df_p_clean
    .sort_values(['order_id', 'payment_value'], ascending=[True, False])
    .drop_duplicates(subset='order_id')  # остаётся по одному payment_type на заказ
    [['order_id', 'payment_type']]
)
payments_main

           order_id payment_type
63665  001gkk6BwKEB  credit_card
58976  0029bAIZFMKA       wallet
31287  002Jk8hp9Bhy       wallet
75687  002ohHsWSKrP  credit_card
50487  0041NijdAYB0  credit_card
...             ...          ...
1888   zznTUG01XP33  credit_card
25107  zzp0E0UK1yAl  credit_card
22248  zzq1nZ4dGR6g  credit_card
81305  zzqZvKoIAsrw       wallet
9200   zzxE4qACYBT2  credit_card

[89186 rows x 2 columns]

In [101]:
fact_orders_finance = fact_orders_finance.merge(
    payments_main,
    on='order_id',
    how='left'
)
fact_orders_finance

,order_id,product_id,price,shipping_charges,total_amount,payment_value,hidden_discount_abs,hidden_discount_pct,payment_ratio_pct,hidden_discount_band,discount_type,payment_type
0,Axfy13Hk4PIk,90K0C1fIyQUf,223.51,84.65,308.16,259.14,49.02,16.0,84.0,10–20%,normal_or_discount,credit_card
1,v6px92oS8cLG,qejhpMGGVcsl,170.80,23.79,194.59,382.39,-187.80,-97.0,197.0,≤0% (нет скидки / переплата),normal_or_discount,credit_card
2,Ulpf9skrhjfm,qUS5d2pEAyxJ,64.40,17.38,81.78,249.25,-167.47,-205.0,305.0,NaN,overpay_or_miscalc,credit_card
3,bwJVWupf2keN,639iGvMyv0De,264.50,30.72,295.22,27.79,267.43,91.0,9.0,50–100%,normal_or_discount,credit_card
4,Dd0QnrMk9Cj5,1lycYGcsic2F,779.90,30.66,810.56,76.15,734.41,91.0,9.0,50–100%,normal_or_discount,credit_card
...,...,...,...,...,...,...,...,...,...,...,...,...
89181,zlcLnXGgAabl,W8vikEizUggJ,31.99,188.65,220.64,128.00,92.64,42.0,58.0,30–50%,normal_or_discount,wallet
89182,IlTAoIkILwrq,KXSbyJWtMMwZ,282.00,1.64,283.64,106.86,176.78,62.0,38.0,50–100%,normal_or_discount,wallet
89183,uA6oXfftGVmT,EG4wDSpFyTth,58.10,4.09,62.19,376.39,-314.20,-505.0,605.0,NaN,overpay_or_miscalc,credit_card
89184,v3QtU6xlGDJp,ZWyg4uNWPHjJ,2899.00,113.01,3012.01,48.05,2963.96,98.0,2.0,50–100%,normal_or_discount,voucher
89185,Xo1fqyXOC6CR,5pbzE0rDy61l,37.88,70.06,107.94,211.93,-103.99,-96.0,196.0,≤0% (нет скидки / переплата),normal_or_discount,credit_card

In [ ]:
# 1. Оставляем только "нормальные" заказы (без сильной переплаты/аномалий)
df_disc = fact_orders_finance[
    fact_orders_finance['discount_type'] == 'normal_or_discount'
].copy()

# 2. Группировка по payment_type с основными метриками по скидкам
discount_by_paytype = (
    df_disc
    .groupby('payment_type')
    .agg(
        orders_count=('order_id', 'nunique'),
        avg_hidden_discount_pct=('hidden_discount_pct ', 'mean'),
        median_hidden_discount_pct=('hidden_discount_pct ', 'median'),
        avg_payment_ratio_pct=('payment_ratio_pct', 'mean')
    )
    .reset_index()
)

# 3. Доля заказов каждого payment_type среди всех "нормальных"
total_orders_disc = discount_by_paytype['orders_count'].sum()
discount_by_paytype['orders_share_pct'] = (
    discount_by_paytype['orders_count'] / total_orders_disc * 100
)

# 4. Округление для удобства чтения
cols_to_round = [
    'avg_hidden_discount_pct',
    'median_hidden_discount_pct',
    'avg_payment_ratio_pct',
    'orders_share_pct'
]
discount_by_paytype[cols_to_round] = discount_by_paytype[cols_to_round].round(2)

discount_by_paytype

# размер скидки не зависит от способа оплаты

,payment_type,orders_count,avg_hidden_discount_pct,median_hidden_discount_pct,avg_payment_ratio_pct,orders_share_pct
0,credit_card,49418,34.34,50.0,65.66,73.56
1,debit_card,975,36.35,50.0,63.65,1.45
2,voucher,3695,37.61,54.0,62.39,5.50
3,wallet,13093,34.95,50.0,65.05,19.49