# Таблица orderitems

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df_oi = pd.read_csv('../raw_data/df_OrderItems.csv')

In [6]:
df_oi.shape

(89316, 5)

In [7]:
df_oi.size

446580

In [8]:
df_oi.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [9]:
df_oi.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [10]:
df_oi.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [11]:
df_oi.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [12]:
df_oi.sample(10)

           order_id    product_id     seller_id   price  shipping_charges
26957  O24c0Nt8Nzu0  8G3cy7YsmwRw  gOTm7A8UNDlQ  420.07             55.54
78822  cLRcMkJQ8Tvq  Biwi1BNtUB7l  r7VxefoTVHbb  509.99             61.16
2549   avcK60Rgy2ph  0b7pcjDGjGnm  YRRzoYYlcm7A  137.88             34.33
80712  MKU1sVOud45l  Axk6HoGiIOa5  KH9VVC2iPaCb  109.82            161.82
15032  gFnrmdq3Qn4I  AhRkdSbf0IC5  fsdM6QZEnGMM  139.33             41.97
78671  DRC5oOCZOgJ9  ezFgSgFLGzVz  l1pYW6GBnPMr  820.00            125.99
18158  Fe9DXK0cDzAV  rOD5s4ESotvQ  lXgFIHCZtrfT  182.90             47.55
4612   qGBR7aIJ9K4a  xjfr5f7tS8ZX  UCE3Mf4XAd26  544.00             22.03
15389  LwRlIG6c2bef  1WpAJOFFhR8N  73jr4z4JJLzT  509.99             47.55
28553  JosJQjySLuR0  T7C3MYkV7qTL  Gj8n4P6E111S  161.00             12.18

In [13]:
# проверим есть ли пустые значения
df_oi.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [14]:
# проверим на уникальность
df_oi.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [15]:
# проверим дубликаты
df_oi.duplicated().sum()

np.int64(0)

In [16]:
# статистика по цифровым показателям
df_oi.describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

In [26]:
# проверим дубли составного ключа
df_oi.groupby(['order_id', 'product_id']).size().shape[0]

89316

In [ ]:
#  посмотрим количество позиций в заказе
df_oi.groupby('order_id').size().describe()

# в каждом заказе ровно по одной позиции, т.е. все заказы однопозиционные

count    89316.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [38]:
# проверим нули в данных
df_oi.query('shipping_charges == 0').order_id.count()

np.int64(22)

In [ ]:
df_oi.query('shipping_charges == 0').describe()

# нулевая доставка (0.025% от общего числа заказов) возможно была из-за самовывоза (дешевые товары)
# или включенной в стоимость товара (дорогие товары)
# в данном датасете нет возможности уточнить этот пункт

             price  shipping_charges
count    22.000000              22.0
mean    236.137273               0.0
std     416.899028               0.0
min      19.980000               0.0
25%      71.800000               0.0
50%     119.070000               0.0
75%     176.145000               0.0
max    1949.900000               0.0

In [43]:
# проверим аномальные цены
quantiles = df_oi[['price', 'shipping_charges']].quantile([0.01, 0.25, 0.5, 0.75, 0.99])
quantiles

        price  shipping_charges
0.01     7.78             1.870
0.25    59.65            20.110
0.50   136.90            35.055
0.75   399.20            57.190
0.99  2899.00           181.880

In [56]:
iqr_price = quantiles.loc[0.75, 'price'] - quantiles.loc[0.25, 'price']
iqe_shipping_charges = quantiles.loc[0.75, 'shipping_charges'] - quantiles.loc[0.25, 'shipping_charges']

In [55]:
low_limit_price = quantiles.loc[0.25, 'price'] - 1.5 * iqr_price
high_limit_price = quantiles.loc[0.75, 'price'] + 1.5 * iqr_price

print(f'Нижняя граница {low_limit_price.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_price.round(2)}')

Нижняя граница -449.68
Верхняя граница 908.53

In [57]:
low_limit_ship_charge = quantiles.loc[0.25, 'shipping_charges'] - 1.5 * iqe_shipping_charges
high_limit_ship_charge = quantiles.loc[0.75, 'shipping_charges'] + 1.5 * iqe_shipping_charges

print(f'Нижняя граница {low_limit_ship_charge.round(2)}', end='\n')
print(f'Верхняя граница {high_limit_ship_charge.round(2)}')

Нижняя граница -35.51
Верхняя граница 112.81

In [ ]:
# кол-во price выше верхней границы
df_oi.query('price > @high_limit_price').shape[0]

5798

In [ ]:
# кол-во shipping_charges выше верхней границы
df_oi.query('shipping_charges > @high_limit_ship_charge').shape[0]

4615

Остановилась на шаге 5 (требуется таблица payments)