# Таблица orders

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_o = pd.read_csv('../raw_data/df_Orders.csv')

In [3]:
df_o.shape

(89316, 7)

In [4]:
df_o.size

625212

In [5]:
df_o.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_timestamp',
       'order_estimated_delivery_date'],
      dtype='str')

In [6]:
df_o.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  str
 1   customer_id                    89316 non-null  str
 2   order_status                   89316 non-null  str
 3   order_purchase_timestamp       89316 non-null  str
 4   order_approved_at              89307 non-null  str
 5   order_delivered_timestamp      87427 non-null  str
 6   order_estimated_delivery_date  89316 non-null  str
dtypes: str(7)
memory usage: 4.8 MB

In [7]:
df_o.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

In [8]:
df_o.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
89311,zlcLnXGgAabl,bfJtzkBGksdY,delivered,2018-08-19 17:25:36,2018-08-21 04:35:30,2018-08-30 14:47:46,2018-09-04
89312,IlTAoIkILwrq,4hjsCpj6FC7g,delivered,2017-12-15 11:20:27,2017-12-16 02:37:32,2017-12-20 19:23:40,2018-01-04
89313,uA6oXfftGVmT,DLn56oKHl9bv,delivered,2018-07-24 06:39:14,2018-07-24 11:20:39,2018-07-27 01:41:40,2018-08-01
89314,v3QtU6xlGDJp,auSfRYUQUOIq,delivered,2018-08-11 08:04:22,2018-08-11 08:24:40,2018-08-14 21:43:51,2018-08-17
89315,Xo1fqyXOC6CR,rhevVNXYJnEs,delivered,2018-06-09 21:46:58,2018-06-09 22:19:00,2018-06-14 15:03:46,2018-07-05

In [9]:
df_o.sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
35366,DiTELsrUizJp,mtdSZbG0tPDi,delivered,2017-11-24 09:46:06,2017-11-25 05:49:39,2017-12-19 21:48:58,2017-12-19
81390,2saNXyHwrIdw,sqgKZRWpjFiJ,delivered,2017-07-11 16:42:15,2017-07-12 06:44:02,2017-07-24 22:22:35,2017-08-02
70635,xaFE9G1LpBZZ,rLYVcjC1iWxB,delivered,2018-05-18 15:33:46,2018-05-19 16:19:11,2018-06-04 19:18:35,2018-06-13
58836,KoDzROw3XCcb,9gkbnl1Bjvpt,delivered,2017-06-22 14:03:48,2017-06-22 14:22:58,2017-07-07 17:47:40,2017-07-14
84782,Hkr7RvMlnCW3,wmfhoXk5E197,delivered,2018-08-12 18:04:00,2018-08-12 18:24:19,2018-08-21 17:41:09,2018-08-27
88070,kK11Mg1ofp5Y,6xSHvgNPmht9,delivered,2017-04-02 10:11:35,2017-04-02 10:25:08,2017-04-17 09:58:04,2017-05-03
1648,Xn8hr3Qe9XwV,tanvsK2c0Cj0,delivered,2017-04-29 20:57:32,2017-04-29 21:10:15,2017-05-22 15:12:13,2017-06-08
65571,PYlcza7STR9v,ntqYOuC7uzgn,processing,2017-12-26 14:03:42,2017-12-27 04:12:34,NaN,2018-01-19
20917,rJYNbvqLnUkl,etrdyxXED34X,delivered,2018-05-18 18:35:01,2018-05-18 18:57:56,2018-06-04 21:53:25,2018-06-19
42788,xEUysE6IMfQ3,CIhAUlRM6nCO,delivered,2018-01-26 11:57:13,2018-01-26 12:21:34,2018-01-31 19:37:49,2018-02-09

In [10]:
df_o.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_timestamp',
       'order_estimated_delivery_date'],
      dtype='str')

In [ ]:
# переименуем колонки для удобства
df_o = df_o.rename(columns={
                   'order_purchase_timestamp': 'purchased_date',
                   'order_approved_at': 'approved_at_date',
                   'order_delivered_timestamp': 'delivered_date',
                   'order_estimated_delivery_date': 'estimated_delivery_date'}
                   )

df_o.columns

Index(['order_id', 'customer_id', 'order_status', 'purchased_date',
       'approved_at_date', 'delivered_date', 'estimated_delivery_date'],
      dtype='str')

In [ ]:
# переопределим тип у колонок с датами
date_cols = [
    'purchased_date',
    'approved_at_date',
    'delivered_date',
    'estimated_delivery_date'
]

df_o[date_cols] = df_o[date_cols].apply(pd.to_datetime)

df_o.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 89316 non-null  str
 1   customer_id              89316 non-null  str
 2   order_status             89316 non-null  str
 3   purchased_date           89316 non-null  datetime64[us]
 4   approved_at_date         89307 non-null  datetime64[us]
 5   delivered_date           87427 non-null  datetime64[us]
 6   estimated_delivery_date  89316 non-null  datetime64[us]
dtypes: datetime64[us](4), str(3)
memory usage: 4.8 MB

In [13]:
# проверим отсутствующие значения
df_o.isna().sum()

# в датасете есть отсутствующие значения, и они достаточно логичны:
# 9 заказов еще ожидает подтверждения
# 1889 заказов еще находятся в пути до клиента

order_id                      0
customer_id                   0
order_status                  0
purchased_date                0
approved_at_date              9
delivered_date             1889
estimated_delivery_date       0
dtype: int64

In [14]:
# проверим дубликаты
df_o.duplicated().sum()

np.int64(0)

In [15]:
# проверим уникальные значения
df_o.nunique()

order_id                   89316
customer_id                89316
order_status                   7
purchased_date             72775
approved_at_date           68215
delivered_date             71143
estimated_delivery_date      444
dtype: int64

In [16]:
df_o['order_status'].unique()

<StringArray>
[  'delivered',    'canceled',     'shipped',  'processing',    'invoiced',
 'unavailable',    'approved']
Length: 7, dtype: str

In [17]:
# переведем данные в столбце 'order_status' в тип данных 'категория'
df_o['order_status'] = df_o['order_status'].astype('category')
df_o.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 89316 non-null  str
 1   customer_id              89316 non-null  str
 2   order_status             89316 non-null  category
 3   purchased_date           89316 non-null  datetime64[us]
 4   approved_at_date         89307 non-null  datetime64[us]
 5   delivered_date           87427 non-null  datetime64[us]
 6   estimated_delivery_date  89316 non-null  datetime64[us]
dtypes: category(1), datetime64[us](4), str(2)
memory usage: 4.2 MB

In [18]:
df_o.describe()

,purchased_date,approved_at_date,delivered_date,estimated_delivery_date
count,89316,89307,87427,89316
mean,2017-12-28 18:48:18.752743,2017-12-29 06:00:09.620600,2018-01-11 07:17:59.921992,2018-01-21 16:16:51.850060
min,2016-09-04 21:15:19,2016-10-04 09:43:32,2016-10-11 13:46:32,2016-10-20 00:00:00
25%,2017-09-08 16:33:39,2017-09-09 08:55:11,2017-09-20 20:10:47.500000,2017-09-29 00:00:00
50%,2018-01-16 16:13:36,2018-01-16 21:51:29,2018-01-30 22:38:23,2018-02-14 00:00:00
75%,2018-05-02 12:20:40,2018-05-02 20:53:52.500000,2018-05-14 15:53:52,2018-05-24 00:00:00
max,2018-09-03 09:06:57,2018-09-03 17:40:06,2018-10-17 13:22:46,2018-10-25 00:00:00

In [19]:
# посмотрим распределение по статусам
status_summary = (
    df_o['order_status']
    .value_counts()
    .to_frame(name='order_count')
    .reset_index()
    .rename(columns={'index': 'order_status'})
)

status_summary['share_pct'] = (
    status_summary['order_count']
    / status_summary['order_count'].sum()
    * 100
)

status_summary = status_summary.sort_values('order_count', ascending=False)

status_summary

  order_status  order_count  share_pct
0    delivered        87428  97.886157
1      shipped          936   1.047965
2     canceled          409   0.457925
3   processing          273   0.305656
4     invoiced          266   0.297819
5     approved            2   0.002239
6  unavailable            2   0.002239

In [20]:
# посмотрим пустые значения в датах
missing_dates = (
    df_o[date_cols]
    .isna()
    .sum()
    .to_frame(name='missing_count')
)

missing_dates['missing_share_pct'] = (
    missing_dates['missing_count']
    / len(df_o)
    * 100
)

missing_dates = missing_dates.sort_values('missing_share_pct', ascending=False)

missing_dates

                         missing_count  missing_share_pct
delivered_date                    1889           2.114963
approved_at_date                     9           0.010077
purchased_date                       0           0.000000
estimated_delivery_date              0           0.000000

In [22]:
# проверяем в каких статусах отсутствуют значения в колонке approved_at
mask = df_o['approved_at_date'].isna()

df_o.loc[mask, 'order_status'].value_counts()

# видим, что у нас имеется 9 доставленных заказов, которые не прошли этап согласования

order_status
delivered      9
approved       0
canceled       0
invoiced       0
processing     0
shipped        0
unavailable    0
Name: count, dtype: int64

In [23]:
# проверяем в каких статусах отсутствуют значения в колонке delivered
mask = df_o['delivered_date'].isna()

df_o.loc[mask, 'order_status'].value_counts()

# в основном пропуски логичные, кроме 6 заказов delivered.
# заказы имеют статус delivered, но при этом отсутствуют даты в столбце delivered

order_status
shipped        936
canceled       404
processing     273
invoiced       266
delivered        6
approved         2
unavailable      2
Name: count, dtype: int64

In [27]:
df_o.columns

Index(['order_id', 'customer_id', 'order_status', 'purchased_date',
       'approved_at_date', 'delivered_date', 'estimated_delivery_date'],
      dtype='str')

In [42]:
# рассчитаем длительность этапов заказа
df_o['dt_purchased_approved'] = (df_o['approved_at_date'] - df_o['purchased_date']).dt.days.astype('float')
df_o['dt_approved_delivered'] = (df_o['delivered_date'] - df_o['approved_at_date']).dt.days.astype('float')
df_o['dt_purchased_estimated'] = (df_o['estimated_delivery_date'] - df_o['purchased_date']).dt.days.astype('float')

df_o.head()

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,0.0,4.0,17.0
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,0.0,13.0,33.0
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,0.0,9.0,19.0
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,0.0,9.0,31.0
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,0.0,14.0,26.0

In [43]:
df_o.dtypes

order_id                              str
customer_id                           str
order_status                     category
purchased_date             datetime64[us]
approved_at_date           datetime64[us]
delivered_date             datetime64[us]
estimated_delivery_date    datetime64[us]
dt_purchased_approved             float64
dt_approved_delivered             float64
dt_purchased_estimated            float64
dtype: object

In [ ]:
# посмотрим основные статистики для разности дат, чтобы выявить аномалии
df_o[['dt_purchased_approved', 'dt_approved_delivered',
       'dt_purchased_estimated']].describe()

# dt_purchased_approved
# минимальное и среднее значение равны нулю => заказы одобряются день-в-день
# но максимальное значение равно 60 дням => редкий кейс или ошибка даты?

# dt_approved_delivered
# минимальное значение отрицательное => доставка раньше, чем одобрение
# максимальное значение 208 дней => отдаленный штат, ошибка даты или сильно проблемный заказ?

# dt_purchased_estimated
# максимальный обещанный срок 149 дней => редкая позиция?
# наверняка этот заказ и доставлялся дольше всего

       dt_purchased_approved  dt_approved_delivered  dt_purchased_estimated
count           89307.000000           87418.000000            89316.000000
mean                0.268579              11.514654               23.529692
std                 0.802292               9.241674                8.863175
min                 0.000000              -7.000000                2.000000
25%                 0.000000               6.000000               18.000000
50%                 0.000000               9.000000               23.000000
75%                 0.000000              15.000000               28.000000
max                60.000000             208.000000              149.000000